[[liboqs]]
arch = "aarch64"
git-tree-sha1 = "805a6e0746ac846ebfb14892db746d7ddd69d0b6"
os = "macos"

    [[liboqs.download]]
    sha256 = "9692501411767921b57778382ed518a2fd6ddf0bcf0082664a40c5832ffea8d8"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.aarch64-apple-darwin.tar.gz"
[[liboqs]]
arch = "aarch64"
git-tree-sha1 = "e1f47aa7053d0ed2812a6f4313651628bf0001c6"
libc = "glibc"
os = "linux"

    [[liboqs.download]]
    sha256 = "b315b647393876515205a20df52d746f5ad79d5699b62adfa29d11f07bfdf3fd"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.aarch64-linux-gnu.tar.gz"
[[liboqs]]
arch = "aarch64"
git-tree-sha1 = "3bd02cec91da1a65efbb8a443ca5ced389255583"
libc = "musl"
os = "linux"

    [[liboqs.download]]
    sha256 = "a99551ddb7b748c3e75eb64d33dd1af3516eae5902fe62cca03f53bcbf22c60c"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.aarch64-linux-musl.tar.gz"
[[liboqs]]
arch = "aarch64"
git-tree-sha1 = "275b4c2c2618a62dc2ffd8f075ae016aed65c083"
os = "freebsd"

    [[liboqs.download]]
    sha256 = "302b5aba0d3feb93c69d40bc5ef0a6d22f8b178071ee8d9927a9b4e85e07e847"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.aarch64-unknown-freebsd.tar.gz"
[[liboqs]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "367c11bdf25e114f8e4167158f1c2ecd9a994c74"
libc = "glibc"
os = "linux"

    [[liboqs.download]]
    sha256 = "60a90a79a0df8e4b879bf026c39009d5daa556b2ff801b8bf18a9ff3be945d64"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.armv6l-linux-gnueabihf.tar.gz"
[[liboqs]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "835e7ea64b85d0a59b02f3d9396b4cdb9308c5ab"
libc = "musl"
os = "linux"

    [[liboqs.download]]
    sha256 = "cb2ab5a9c75f2c340a2c1416d1dca6df29fedf7db05ee891429945c3c9259f21"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.armv6l-linux-musleabihf.tar.gz"
[[liboqs]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db9fdcbebb7c84fa9784418989ce207e0e3213eb"
libc = "glibc"
os = "linux"

    [[liboqs.download]]
    sha256 = "30f6e184b7d7694d2e91fb706781b2ee69e8e731e62e841c95d0d127933bb993"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.armv7l-linux-gnueabihf.tar.gz"
[[liboqs]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b97741ac0a4abdf00c9c25e56fe13c6fcfac398f"
libc = "musl"
os = "linux"

    [[liboqs.download]]
    sha256 = "693f2887da0d44795f7717d74933255726cf82678a52e8e33b0c6cb38bb1424f"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.armv7l-linux-musleabihf.tar.gz"
[[liboqs]]
arch = "i686"
git-tree-sha1 = "f636a7a90cb36e4550d34a1386f6c734a93c8111"
libc = "glibc"
os = "linux"

    [[liboqs.download]]
    sha256 = "ba85bb03a16964131ba1db579dbbac395b04cd7790eff3a2e30ff9adec07665b"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.i686-linux-gnu.tar.gz"
[[liboqs]]
arch = "i686"
git-tree-sha1 = "f7ae42f304c14cc26e3bf1095c45de4e7792d160"
libc = "musl"
os = "linux"

    [[liboqs.download]]
    sha256 = "af7e11baba4707aeedd53d13ce69c000803ec3dc19573e230924b42c48a657bd"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.i686-linux-musl.tar.gz"
[[liboqs]]
arch = "i686"
git-tree-sha1 = "0cc115b2a7bffd11ba227bc1321a0fb22acd6569"
os = "windows"

    [[liboqs.download]]
    sha256 = "1802f4a832216c569106582a8b9920b6c033ffd1da6f39214a8a7b7e920b4a7a"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.i686-w64-mingw32.tar.gz"
[[liboqs]]
arch = "x86_64"
git-tree-sha1 = "71059091d18489c0f411285c0f55fb76ed3ea460"
os = "macos"

    [[liboqs.download]]
    sha256 = "cffbf97bc33e93c231d411793a9babc82f1cf118b615da843fd05faeffc828af"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.x86_64-apple-darwin.tar.gz"
[[liboqs]]
arch = "x86_64"
git-tree-sha1 = "b2ed425d4cfc73527f3f6179fa04f2a0798d28c5"
libc = "glibc"
os = "linux"

    [[liboqs.download]]
    sha256 = "1650e9ec6058a96f42f17af5d226fc07c3bef92aed9b3fccc86fb635462b83e3"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.x86_64-linux-gnu.tar.gz"
[[liboqs]]
arch = "x86_64"
git-tree-sha1 = "77d43f62dd02c52ced7f572f981fc8df1a2801b1"
libc = "musl"
os = "linux"

    [[liboqs.download]]
    sha256 = "9a0285ce0af354f46e417b153f2086c844456de7cf4759f3a760bfda87088470"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.x86_64-linux-musl.tar.gz"
[[liboqs]]
arch = "x86_64"
git-tree-sha1 = "2e0d746f893bf10ef8935ff0bef3de0d03b07481"
os = "freebsd"

    [[liboqs.download]]
    sha256 = "746ac195fde44aaa12f06d082ba28924323db8675f91d5976b4452ab3acdc74f"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.x86_64-unknown-freebsd.tar.gz"
[[liboqs]]
arch = "x86_64"
git-tree-sha1 = "f9de7cb9c9209a6739523eab4a761ebdab815d3a"
os = "windows"

    [[liboqs.download]]
    sha256 = "93895ff49206a9e1381c637f73c90b6710318829ed7575c7a5b396a1ef497075"
    url = "https://github.com/terasakisatoshi/liboqs_jll.jl/releases/download/liboqs-v0.14.0+0/liboqs.v0.14.0.x86_64-w64-mingw32.tar.gz"
