# Autogenerated wrapper script for liboqs_jll for aarch64-apple-darwin
export liboqs

JLLWrappers.@generate_wrapper_header("liboqs")
JLLWrappers.@declare_library_product(liboqs, "@rpath/liboqs.8.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liboqs,
        "lib/liboqs.0.14.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
