# Autogenerated wrapper script for liboqs_jll for i686-w64-mingw32
export liboqs

JLLWrappers.@generate_wrapper_header("liboqs")
JLLWrappers.@declare_library_product(liboqs, "liboqs.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        liboqs,
        "bin\\liboqs.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
