# Autogenerated wrapper script for liboqs_jll for x86_64-linux-musl
export liboqs

using OpenSSL_jll
JLLWrappers.@generate_wrapper_header("liboqs")
JLLWrappers.@declare_library_product(liboqs, "liboqs.so.8")
function __init__()
    JLLWrappers.@generate_init_header(OpenSSL_jll)
    JLLWrappers.@init_library_product(
        liboqs,
        "lib/liboqs.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
